config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'books#index'
  resources :books do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :comments

    def self.search(search)
        if search != ""
          Book.where('text LIKE(?) OR topic LIKE(?) OR name LIKE(?) OR user_id LIKE(?)',"%#{search}%","%#{search}%","%#{search}%","%#{search}%")
        else
          Book.all
        end
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :book  
    belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, foreign_key: :user_id, dependent: :destroy
  has_many :comments, foreign_key: :user_id, dependent: :destroy        
  
  validates :nicknmame, presence: true
  validates :email, presence: true,
                    uniqueness: true
  validates :password,presence: true,
                      length: { minimum: 6 },
                      format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i}
  validates :first_name, presence: true, 
                         format: { with: /\A[ぁ-んァ-ン一-龥]/}
  validates :last_name, presence: true,
                        format: { with: /\A[ぁ-んァ-ン一-龥]/}
  validates :first_name_kana, presence: true, 
                              format: { with: /\A[ァ-ヶー－]+\z/}
  validates :last_name_kana, presence: true,
                            format: { with: /\A[ァ-ヶー－]+\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :basic_auth
    before_action :configure_permitted_parameters, if: :devise_controller?

    private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:first_name_kana,:last_name_kana,:nicknmame])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email,:password])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :move_to_index, except: [:index, :show, :search]
    before_action :set_item, only: [:show, :edit,:update,:destroy]

    def index
        @books = Book.all.order("created_at DESC")
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if @book.save
            redirect_to root_path
            else
            render :index
        end
    end

    def show
      @comment = Comment.new
      @comments = @book.comments.order("created_at DESC").includes(:user)
    end

    def edit
    end
  
    def update    
      if @book.update(book_params)
        redirect_to root_path
      else
        render :edit
      end
    end

    def destroy
        if @book.destroy
        redirect_to root_path
        else
          render :show
        end
    end

    def search
      @books = Book.search(params[:keyword])
    end

    private
    def book_params
        params.require(:book).permit(:name,:topic,:image,:text).merge(user_id: current_user.id)
    end

    def set_item
        @book = Book.find(params[:id])
    end


    def move_to_index
        unless user_signed_in?
          redirect_to action: :index
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        comment = Comment.create(comment_params)
        redirect_to "/books/#{comment.book.id}" 
    end
    
    private
    def comment_params
        params.require(:comment).permit(:text).merge(user_id: current_user.id, book_id: params[:book_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        user = User.find(params[:id])
        @books = user.books.order("created_at DESC")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="contents-post">
  <div class="container">
  
    <h3 class="new-title">編集画面</h3>
    
    <%= form_with(model: @book, local: true) do |form| %>

      <div class="form-name">
      <%= form.text_field :name, placeholder: "Book name",size: "70" ,class:"name-box"%>
      </div>

      <div class="form-title">
      <%= form.text_field :topic, placeholder: "Sub title",size: "70",class:"title-box" %>
      </div>
      
      <div class="form-url">
      <%= form.text_field :image, placeholder: "Image-url",size: "70" ,class:"url-box"%>
      </div>
      
      <div class="form-text">
      <%= form.text_area :text, placeholder: "text",size: "70x15",class:"text-box" %>
      </div>
      
      <div class="form-send">
      <%= form.submit "編集",class:"submit-box"%>
      </div>
  
    <% end %>
  
  </div>
</div>

app/views/books/index.html.erb
<div class= "serach-sample">
<%= form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "キーワードを入力",size: "35", class: "search-input" %>
  <%= form.submit "検索",class: "search-btn" %>
<% end %>
</div>
<div class="contents-row" >
  <% @books.each do |book| %>
    <div class="sample-middle">
   <div class="contet-middle" id="context">
    <%= link_to  book_path(book.id),method: :get do %>
    <div class="book-image">
    <%= image_tag book.image, class: "book-img", :size => '100x100' %>
    </div>
    <div class="book-info">
      <p class="book-name"><%= book.name %></p>
      <p class="topic-name"><%= book.topic %></p>
    <% end %>
    <div class="name">
      <a class="user-name" href="/users/<%= book.user.id %>">
          <span>投稿者：<%= book.user.nicknmame %></span>
          <% weeks = ["日","月","火","水","木","金","土"]%>
          <% week = weeks[book.created_at.wday]%>
          <span class="tweet-time"><%= book.created_at.strftime("%y20/%m/%d(#{week}):%H:%M")%></span>
      </a>
    </div>
    </div>
    </div>
   </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="contents-post">

  <h3 class="new-title">新規投稿情報</h3>

  <div class="container">
    
    <div class="new-post">
    <%= form_with(model: @book, local: true) do |form| %>

      <div class="form-name">
      <%= form.text_field :name, placeholder: "書籍名",size: "70" ,class:"name-box"%>
      </div>

      <div class="form-title">
      <%= form.text_field :topic, placeholder: "自分なりのサブタイトルをつけてみましょう",size: "70",class:"title-box" %>
      </div>
      
      <div class="form-url">
      <%= form.text_field :image, placeholder: "画像URL",size: "70" ,class:"url-box"%>
      </div>
      
      <div class="form-text">
      <%= form.text_area :text, placeholder: "本文",size: "70x15",class:"text-box" %>
      </div>
      
      <div class="form-send">
      <%= form.submit "投稿",class:"submit-box"%>
      </div>
  
    <% end %>
    </div>
    </div>
</div>

app/views/books/search.html.erb
<%= form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "キーワードを入力",size: "35", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents-row">
  <% @books.each do |book| %>
   <div class="contet-middle">
    <%= link_to  book_path(book.id),method: :get do %>
    <div class="book-image">
    <%= image_tag book.image, class: "book-img", :size => '100x100' %>
    </div>
    <div class="book-info">
      <p class="book-name"><%= book.name %></p>
      <p class="topic-name"><%= book.topic %></p>
    <% end %>
    <div class="name">
      <a class="user-name" href="/users/<%= book.user.id %>">
          <span>投稿者：<%= book.user.nicknmame %></span>
          <% weeks = ["日","月","火","水","木","金","土"]%>
          <% week = weeks[book.created_at.wday]%>
          <span class="tweet-time"><%= book.created_at.strftime("%y20/%m/%d(#{week}):%H:%M")%></span>
      </a>
    </div>
    </div>
   </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class= "serach-sample">
<%= form_with(url: search_books_path, local: true, method: :get, class: "search-show") do |form| %>
  <%= form.text_field :keyword, placeholder: "キーワードを入力",size: "35", class: "search-input" %>
  <%= form.submit "検索",class: "search-btn" %>
<% end %>
</div>
<div class="book-explain-box">
   <div class="top-message">
    <div class="sample-message">
    <div class="book-image">
     <%= image_tag @book.image, class: "book-img", :size => '165x190' %>
    </div>
    <div class="book-info">
      <div class="sample">
      <p class="book-name"><%= @book.name %></p>
      <p class="topic-name"><%= @book.topic %></p>
      </div>
      </div>
    </div>
    </div>

    <div class="book-text">

    <div class="text-header">
    <div class="header-message">
   
    <div class="text-title">
    レビュー
    </div>

    <div class="select-btn">
    <% if user_signed_in? && current_user.id == @book.user_id %>
    <div class="edit-btn">
    <%= link_to '編集', edit_book_path(@book.id), method: :get, class: "book-red-btn" %>
    </div>
    <div class="delete-btn">
    <%= link_to '削除', book_path(@book.id), method: :delete, class:'book-destroy' %>
    </div>
    <%else%>
      <div class="review-user">
      <a class="review-total" href="/users/<%= @book.user.id %>">
        <span class="left-title">by</span>
        <span class="right-title"><%= @book.user.nicknmame %></span>
      </a>
      </div>
    <% end %>
    </div>
    </div>
    <p class="text-name"><%=safe_join(@book.text.split("\n"),tag(:br)) %></p>
    </div>
    </div>

    <div class="container-comment">
    <div class="sample-comment">

    <% if current_user %>
      <%= form_with(model: [@book, @comment], local: true) do |form| %>
        <div class= "comment-box">
        <%= form.text_area :text, placeholder: "コメントする",class:"comment-second",id: "form-date"%>
        </div>
        <div class="comment-sendbtn">
        <%= form.submit "SEND",class:"comment-forword",id: "submit" %>
        </div>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
       <div class="comments">
       <div class="comment-title">
       ＜コメント一覧＞
      </div>

      <div id="list">
      </div> 

      <div class="comment-main">
      <% if @comments %>
        <% @comments.each do |comment| %>
           <div class="main-sample">
           <div class="main-essance">
            <div class="second-block">
            <span class="comment-username">
            <%= link_to comment.user.nicknmame, "/users/#{comment.user_id}",class:'comment-orner' %>
            </span>
            </div>
            
            <div class="comment-context">
            <%= safe_join(comment.text.split("\n"),tag(:br))%>
            <% weeks = ["日","月","火","水","木","金","土"]%>
            <% week = weeks[comment.created_at.wday]%>
            <span class="comment-time"><%= comment.created_at.strftime("%y20/%m/%d(#{week}):%H:%M")%></span>
            </div>
            </div>
            </div>
        <% end %>
      <% end %>
      </div>

    </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booktweet29265</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="change.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/0ff4165df8.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  </head>

  <body>
      <header class="header">
      <div class="header_bar">
        <h1 class="main-title">
        <span class="fas fa-feather icon-bird" ></span>
        <a class='title-name' href="/">BookTweet</a></h1>
        <% if user_signed_in? %>
          <div class="second-message">
           <span class="user-message">
           <%= current_user.nicknmame %>
           <ul class="user-info" id="user-acount">
            <li>
             <%= link_to "マイページ", "/users/#{current_user.id}",class: "my-page" %>
             <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "log-out"%>
            </li>
              <script>
                        if ($('.menu').hasClass('fal fa-times delete')){
                        $('.menu').removeClass('fal fa-times delete');
                        
                        $('.delete').addClass('fa fa-bars menu');
                        $('.display-list').fadeOut();
                        $('.list').css('display','none');
                    
                    }else{

                        $('.display-list').fadeIn();
                        $('.list').css('display','block');
                        $('.menu').addClass('fal fa-times delete');
                  }
                });

            </script>
           </ul>
          </span>
          <%= link_to "投稿する", new_book_path, class: "post" %>
                  
          </div>

        <% else %>
          <div class="third-massegae">
            <span class="log-box">
            <%= link_to "ログイン", new_user_session_path, class: "log-in" %>
            </span>
            <span class="sign-box">
            <%= link_to "新規登録", new_user_registration_path, class: "sign-up" %>
            </span>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <script src="namecolor.js"></script>
  </body>
</html>

app/views/users/show.html.erb
<%= form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "キーワードを入力",size: "35", class: "search-input" %>
  <%= form.submit "検索",class: "search-btn" %>
<% end %>

<div class="user-profile">
</div>

<div class="contents-row">
  <% @books.each do |book| %>
   <div class="contet-middle">
    <%= link_to  book_path(book.id),method: :get do %>
    <div class="book-image">
    <%= image_tag book.image, class: "book-img", :size => '100x100' %>
    </div>
    <div class="book-info">
      <p class="book-name"><%= book.name %></p>
      <p class="topic-name"><%= book.topic %></p>
      <div class="name">
      <a class="user-name" href="/users/<%= book.user.id %>">
          <% weeks = ["日","月","火","水","木","金","土"]%>
          <% week = weeks[book.created_at.wday]%>
          <span class="tweet-time"><%= book.created_at.strftime("%y20/%m/%d(#{week}):%H:%M")%></span>
      </a>
      </div>
    </div>
    <%end%>
   </div>
  <% end %>
</div>